function spiketimes = spiketrain_poisson_n(lambda, N, timeresolution)
% SPIKETRAIN_POISSON_N - Return a Poisson spike train with N spikes
%
%    SPIKETIMES = vlt.neuroscience.spiketrains.spiketrain_poisson_n(LAMBDA, N, TIMERESOLUTION)
%
%   Returns a list of SPIKETIMES of length N that are generated by a
%   Poisson process with mean rate LAMBDA and time resolution 
%   TIMERESOLUTION.
%
%   Example:
%       lambda = 10; % 10Hz
%       timeres = 0.001; % 1ms bins
%       spiketimes = spiketrain_posson_n(lambda, 10, timeres);
%       % returns 10 spikes distributed in a Poisson manner with rate
%       % 10Hz, 1ms bins

 % abitrarily, let's build these in 1 second chunks

spiketimes = [];

T_offset = 0;

bins = 0:timeresolution:1-timeresolution;

while (length(spiketimes)<N),

	spikebins = (rand(length(bins),1))<(timeresolution*lambda);
	spiketimes_new = bins(find(spikebins))+T_offset;
	
	spiketimes = [spiketimes spiketimes_new];

	T_offset = T_offset + 1;
end;

spiketimes = spiketimes(1:N); % return first N spikes

