function test_cell2mlstr()
% TEST_CELL2MLSTR - Test for vlt.data.cell2mlstr
%
    % Test case 1: Simple case
    A = {'test', 5, [3 4 5]};
    str = vlt.data.cell2mlstr(A);
    expected_str = ['<CELL size=[1 3] data=' sprintf('\n') ...
        '     <''test''>' sprintf('\n') ...
        '     <[5]>' sprintf('\n') ...
        '     <[3 4 5]>' sprintf('\n') ...
        '/CELL>'];
    assert(strcmp(str, expected_str), 'The XML string is not correct');

    % Test case 2: Nested cell
    A = {'test', {5, 6}};
    str = vlt.data.cell2mlstr(A);
    expected_str = ['<CELL size=[1 2] data=' sprintf('\n') ...
        '     <''test''>' sprintf('\n') ...
        '     <' ...
        '<CELL size=[1 2] data=' sprintf('\n') ...
        '          <[5]>' sprintf('\n') ...
        '          <[6]>' sprintf('\n') ...
        '     /CELL>' ...
        '>' sprintf('\n') ...
        '/CELL>'];
    assert(strcmp(str, expected_str), 'The XML string for the nested cell is not correct');

    disp('All tests for vlt.data.cell2mlstr passed.');
end
