classdef cell2mlstrTest < matlab.unittest.TestCase
    methods (Test)
        function testSimpleCell(testCase)
            A = {'test', 5, [3 4 5]};
            str = vlt.data.cell2mlstr(A);
            expected_str = ['<CELL size=[1 3] data=' sprintf('\n') ...
                '     <''test''>' sprintf('\n') ...
                '     <[5]>' sprintf('\n') ...
                '     <[3 4 5]>' sprintf('\n') ...
                '/CELL>'];
            testCase.verifyEqual(str, expected_str);
        end

        function testNestedCell(testCase)
            A = {'test', {5, 6}};
            str = vlt.data.cell2mlstr(A);
            expected_str = ['<CELL size=[1 2] data=' sprintf('\n') ...
                '     <''test''>' sprintf('\n') ...
                '     <' ...
                '<CELL size=[1 2] data=' sprintf('\n') ...
                '          <[5]>' sprintf('\n') ...
                '          <[6]>' sprintf('\n') ...
                '     /CELL>' ...
                '>' sprintf('\n') ...
                '/CELL>'];
            testCase.verifyEqual(str, expected_str);
        end
    end
end
