% Demonstration script for calculating responses and fits of speed tuning
% curve

% 1. Select a set of spatial frequencies SF and temporal frequencies TF to
% pair
[SF,TF] = meshgrid([0.05 0.08 0.1 0.2 0.4 0.8 1.2],[0.5 1 2 4 8 16 32]);

% 2. Select some parameters of an example tuning curve; see help
% vlt.neuro.vision.speed.tuningfunc for definitions
%  P = [A zeta xi sigma_sf sigma_tf sf0 tf0]
P = [50 0 0.2  0.1 1 0.2 2];

% 3. Generate speed tuning curve based purely on the function parameters
R = vlt.neuro.vision.speed.tuningfunc(SF,TF,P);

% 4. Plot the curve
figure;
vlt.neuro.vision.speed.plottuning(SF,TF,R);
title('Original');

% 5. Fit the curve using a fitting function, pretending that the parameters
% that generated it are unknown
P_ = vlt.neuro.vision.speed.fit(SF,TF,R);
P_ = P_.'; % Make it a row vector so that P and P_ can be concatenated

% 6. Plot the fit on the tuning curve
figure;
R_ = vlt.neuro.vision.speed.tuningfunc(SF,TF,P_);
vlt.neuro.vision.speed.plottuning(SF,TF,R_,'linestyle','-');
title('Fit');

% 7. Numerically compare the known parameters with the parameters that were
% generated by the fit; they should match
[P;P_] % Currently, P_ = [50.0000 -0.0000 0.3340 0.1365 1.0000 0.2000 2.0000]
