function textbox(title, str)
% TEXTBOX - Display a string in a window and wait for a click in an OK box
%
%  vlt.ui.textbox(TITLE,STR)
%
%  Displays the text in the string STR in a new window with title TITLE.
%  The only button is an OK button to dismiss the window.
%

h0 = figure('Color',[0.8 0.8 0.8], ...
        'PaperUnits','points', ...
        'Position',[200 200 650 590], ...
        'Tag','Fig1', ...
	'MenuBar','none','Name',title);
lb = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[1 1 1], ...
        'Position',[0.4 68.8 500 400.4], ...
        'String',' ', ...
        'Style','listbox', ...
        'Tag','Listbox1', ...
        'Value',[],'Max',2,'FontName','Courier');
ok = uicontrol('Parent',h0, ...
        'Units','points', ...
        'BackgroundColor',[0.7 0.7 0.7], ...
        'ListboxTop',0, ...
        'Position',[192.8 28 67.2 24.8], ...
        'String','OK', ...
        'Tag','Pushbutton1', ...
	'Callback', 'close(gcbf)');

if iscell(str),
    g = textwrap(lb,str);
else,
    g = textwrap(lb,{str});
end;
set(lb,'String',g);
